# Generated by Django 4.1.3 on 2022-11-22 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_no_of_players', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_no_of_players', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('summary', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Rented')], default='a', max_length=1)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bored_games_app.boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bored_games_app.boardgame')),
                ('review_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rented', models.DateField(auto_now_add=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bored_games_app.boardgameinstance')),
            ],
        ),
    ]
